CREATE TABLE clients
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    name       VARCHAR(120) NOT NULL,
    email      VARCHAR(150) NOT NULL,
    cpf        VARCHAR(20),
    status     VARCHAR(255) NOT NULL,
    score      INTEGER      NOT NULL,

    CONSTRAINT uq_clients_email UNIQUE (email),
    CONSTRAINT uq_clients_cpf UNIQUE (cpf)
);