CREATE TABLE products
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,

    product_name VARCHAR(150)   NOT NULL,
    price        NUMERIC(10, 2) NOT NULL,
    stock        INTEGER        NOT NULL,
    active       BOOLEAN        NOT NULL,
    category     VARCHAR(50)
);
