CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,

    client_id   BIGINT       NOT NULL,
    status      VARCHAR(255) NOT NULL,
    total_price NUMERIC(12, 2),

    CONSTRAINT fk_orders_client
        FOREIGN KEY (client_id)
            REFERENCES clients (id)
);
